### ISSUE TITLE
Change method of some API with avax prefix to ezc

### ISSUE THREAD

**Issue by nguyenduybinh** [ROIchain/ezcgo#7]
Some API method have avax prefix need to change to ezc, in details:
- avm Import Avax
- evm export Avax
- evm export
- evm export key
- evm get atomictx
- evm get atocmictx status
- evm get utxos
- evm import
- evm import avax
- emv import key
- evm issuetx
- PlatformVM Export/Import Avax

**Comment by enixdark** [comment]
@diepmv please support this issue.

**Comment by diepmv** [comment]
I made a PR [https://github.com/ROIchain/coreth/pull/7](url), help me review @enixdark @nguyenduybinh

**Comment by nguyenduybinh** [comment]
I tested the pull request in coreth repo OK, so closed this issue. Thanks @diepmv for support
